server:
  port: 8081
  servlet:
    context-path: /api/v1

event:
  publisher:
    rate: 5000

user:
  event:
    queue:
      user-created: user_created

spring:
  application:
    name: user
  datasource:
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/tdc_outbox
  jpa:
    hibernate:
      ddl-auto: create
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin